/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BrowserPicker: typeof import('./src/components/BrowserPicker.vue')['default']
    CategoryContextMenu: typeof import('./src/components/CategoryContextMenu.vue')['default']
    CategoryItemContextMenu: typeof import('./src/components/CategoryItemContextMenu.vue')['default']
    DemoVideoDialog: typeof import('./src/components/DemoVideoDialog.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IconPicker: typeof import('./src/components/IconPicker.vue')['default']
    IconSelectron: typeof import('./src/components/IconSelectron.vue')['default']
    LaunchItem: typeof import('./src/components/LaunchItem.vue')['default']
    LaunchList: typeof import('./src/components/LaunchList.vue')['default']
    ListContextMenu: typeof import('./src/components/ListContextMenu.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    ListItemContextMenu: typeof import('./src/components/ListItemContextMenu.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCol: typeof import('naive-ui')['NCol']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvide: typeof import('naive-ui')['NDialogProvide']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NDynamicTags: typeof import('naive-ui')['NDynamicTags']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NRow: typeof import('naive-ui')['NRow']
    NSelect: typeof import('naive-ui')['NSelect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    OpenDemoVideo: typeof import('./src/components/OpenDemoVideo.vue')['default']
    OperationCategoryModal: typeof import('./src/components/OperationCategoryModal.vue')['default']
    OperationLaunchModal: typeof import('./src/components/OperationLaunchModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
