//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "autocomplete_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub query: String,
    pub usage_count: Option<i32>,
    #[sea_orm(column_type = "custom(\"DATETIME\")", nullable)]
    pub last_used_at: Option<String>,
    pub launch_item_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
  #[sea_orm(
        belongs_to = "super::launch_items::Entity",
        from = "Column::LaunchItemId",
        to = "super::launch_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LaunchItems,
}

impl Related<super::launch_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LaunchItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
