//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use chrono::Utc;
use sea_orm::{entity::prelude::*, ActiveModelBehavior, ActiveValue::Set};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, serde::Serialize)]
#[sea_orm(table_name = "categories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    pub parent_id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub association_directory: Option<String>,
    pub exclude: bool,
    #[sea_orm(column_type = "Text", default_value = "grid")]
    pub layout: String,

    #[sea_orm(column_type = "Text", default_value = "default")]
    pub sort_by: String,

    #[sea_orm(column_type = "Text", default_value = "default")]
    pub sort_order: String,

    #[sea_orm(column_type = "Text", nullable)]
    pub icon: Option<String>,

    #[sea_orm(default_value = 0, nullable)]
    pub order_index: Option<i32>,

    #[sea_orm(column_type = "Text", nullable)]
    pub pinyin_full: Option<String>,

    #[sea_orm(column_type = "Text", nullable)]
    pub pinyin_abbr: Option<String>,

    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
}

#[async_trait::async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        let now = Utc::now().timestamp_millis();
        if insert {
            self.created_at = Set(now);
        }
        self.updated_at = Set(now);
        Ok(self)
    }
}
