//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::{entity::prelude::*, ActiveModelBehavior};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, serde::Serialize)]
#[sea_orm(table_name = "categories")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", unique)]
    pub name: String,
    pub parent_id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub association_directory: Option<String>,
    pub exclude: bool,
    #[sea_orm(column_type = "Text", default_value = "grid")]
    pub layout: String,

    #[sea_orm(column_type = "Text", default_value = "time")]
    pub sort_by: String,

    #[sea_orm(column_type = "Text", default_value = "asc")]
    pub sort_order: String,

    #[sea_orm(column_type = "Text", nullable)]
    pub icon: Option<String>,

    #[sea_orm(default_value = 0, nullable)]
    pub order_index: Option<i32>,

    #[sea_orm(column_type = "custom(\"DATETIME\")", nullable)]
    pub created_at: Option<String>,

    #[sea_orm(column_type = "custom(\"CURRENT_TIMESTAMP\")", nullable)]
    pub updated_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    SelfRef,
}

impl ActiveModelBehavior for ActiveModel {}
