//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "launch_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub launch_item_id: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub path: String,
    #[sea_orm(column_type = "Text")]
    pub status: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub message: Option<String>,
    #[sea_orm(column_type = "custom(\"DATETIME\")", nullable)]
    pub started_at: Option<String>,
    #[sea_orm(column_type = "custom(\"DATETIME\")", nullable)]
    pub ended_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::launch_items::Entity",
        from = "Column::LaunchItemId",
        to = "super::launch_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LaunchItems,
}

impl Related<super::launch_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LaunchItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
