//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "launch_items")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub lnk_name: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub path: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub icon: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub hotkey: Option<String>,
    pub hotkey_global: Option<bool>,
    #[sea_orm(column_type = "Text", nullable)]
    pub pinyin_full: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub pinyin_abbr: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub keywords: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub start_dir: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub remarks: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub args: Option<String>,
    pub run_as_admin: Option<bool>,
    pub order_index: Option<i32>,
    pub enabled: Option<bool>,
    pub category_id: Option<i32>,
    pub subcategory_id: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub extension: Option<String>,
    pub launch_count: Option<i32>,
    pub failure_count: Option<i32>,
    #[sea_orm(column_type = "custom(\"DATETIME\")", nullable)]
    pub last_used_at: Option<String>,
    #[sea_orm(column_type = "custom(\"DATETIME\")", nullable)]
    pub created_at: Option<String>,
    #[sea_orm(column_type = "custom(\"DATETIME\")", nullable)]
    pub updated_at: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::categories::Entity",
        from = "Column::SubcategoryId",
        to = "super::categories::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Categories2,
    #[sea_orm(
        belongs_to = "super::categories::Entity",
        from = "Column::CategoryId",
        to = "super::categories::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Categories1,
    #[sea_orm(has_many = "super::launch_history::Entity")]
    LaunchHistory,
    #[sea_orm(has_many = "super::autocomplete_history::Entity")]
    AutocompleteHistory,
}

impl Related<super::launch_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LaunchHistory.def()
    }
}

impl Related<super::autocomplete_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AutocompleteHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
