//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::autocomplete_history::Entity as AutocompleteHistory;
pub use super::categories::Entity as Categories;
pub use super::configs::Entity as Configs;
pub use super::launch_history::Entity as LaunchHistory;
pub use super::launch_items::Entity as LaunchItems;
